import "./App.css";
import React from "react";
import { Switch, BrowserRouter as Router, Route } from "react-router-dom";
import DESKTOP from "./components/DESKTOP";
import NOTEBOOK from "./components/NOTEBOOK";
import TABLET from "./components/TABLET";
import MOBILE from "./components/MOBILE";

function App() {
  return (
    <Router>
      <Switch>
        <Route path="/:path(|desktop)">
          <DESKTOP {...dESKTOPData} />
        </Route>
        <Route path="/notebook">
          <NOTEBOOK {...nOTEBOOKData} />
        </Route>
        <Route path="/tablet">
          <TABLET {...tABLETData} />
        </Route>
        <Route path="/mobile">
          <MOBILE {...mOBILEData} />
        </Route>
      </Switch>
    </Router>
  );
}

export default App;
const group212Data = {
    className: "group-1",
};

const group213Data = {
    className: "group-1",
};

const group214Data = {
    className: "group-15",
};

const group215Data = {
    className: "group-1",
};

const group216Data = {
    className: "group-1",
};

const group218Data = {
    className: "group-1",
};

const group219Data = {
    className: "group-1",
};

const dESKTOPData = {
    dao_Blockchain_Projects1: "SOME",
    dao_Blockchain_Projects2: "DAILY FOLLOW-UP COURSES",
    graph2: "/img/graph2-1@2x.png",
    course_Topics1: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description1: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent1: "~30%",
    course_Topics2: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description2: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent2: "~30%",
    course_Topics3: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description3: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent3: "~30%",
    dao_Blockchain_Projects3: <React.Fragment>WELCOME TO MY BLOCKCHAIN UNIVERSE!<br />HERE IS MY OWN PLACE TO MAKE SURE THAT I’M REALLY DEVELOPING CODES, STUDYING AND LEARNING ABOUT BLOCKCHAIN.</React.Fragment>,
    spanText1: <React.Fragment>THE PLAN IS NOT TO BE PRETTY. <br />AYANAVERSE IS A HANDS-ON PLACE, THEN IT’S SIMPLE, BUT<br />BELIEVE ME, IT CAN BE A WONDERFUL PLACE FOR WHO WANTS TO DEVELOP A NEW HARDSKILL</React.Fragment>,
    spanText2: " within a fairly short time.",
    ayana_Droid: "/img/ayana-droid-1@1x.png",
    redes_Socias1: "/img/redes-socias-1@2x.png",
    redes_Socias2: "/img/redes-socias-2@2x.png",
    redes_Socias3: "/img/redes-socias-3@2x.png",
    dao_Blockchain_Projects4: "MY BLOCKCHAIN PROJECTS",
    dao_Blockchain_Projects5: "DAO BLOCKCHAIN",
    number1: "PROJECT #01",
    title1: <React.Fragment>BLOCKCHAIN VACCINE VERIFICATION<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status1: "IN PROGRESS",
    number2: "PROJECT #02",
    title2: <React.Fragment>BLOCKCHAIN FOR SUPPLY CHAIN MANAGEMENT<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status2: "IN PROGRESS",
    number3: "PROJECT #03",
    title3: <React.Fragment>BLOCKCHAIN VOTING APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status3: "IN PROGRESS",
    number4: "PROJECT #04",
    title4: <React.Fragment>BLOCKCHAIN SOCIAL MEDIA APP <br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status4: "IN PROGRESS",
    defi_Blockchain_Projects: "DEFI BLOCKCHAIN",
    number5: "PROJECT #01",
    title5: <React.Fragment>CRYPTOCURRENCY FINANCE PRICE TRACKER<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status5: "IN PROGRESS",
    number6: "PROJECT #02",
    title6: <React.Fragment>BUILD YOUR OWN ETHERSCAN<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status6: "IN PROGRESS",
    number7: "PROJECT #03",
    title7: <React.Fragment>CRYPTOCURRENCY APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status7: "IN PROGRESS",
    number8: "PROJECT #04",
    title8: <React.Fragment>DEFI DASHBOARD ON AVALANCHE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status8: "IN PROGRESS",
    nft_Blockchain_Projects: "NFT BLOCKCHAIN",
    number9: "PROJECT #01",
    title9: <React.Fragment>NFT SMART CONTRACT ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status9: "IN PROGRESS",
    number10: "PROJECT #02",
    title10: <React.Fragment>CREATE GENERATIVE NFTS: ARTWORKS CODE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status10: "IN PROGRESS",
    number11: "PROJECT #03",
    title11: <React.Fragment>FULL WEB3 MINT WEBSITE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status11: "IN PROGRESS",
    number12: "PROJECT #04",
    title12: "",
    fullStackNftMarke: <React.Fragment>FULL STACK NFT MARKETPLACE ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status12: "IN PROGRESS",
    dao_Blockchain_Projects6: "NEXT NFT RELEASES",
    eth1: "/img/eth@2x.png",
    surname1: "PRICE",
    collection1: "X-FEMME",
    number13: "X-FEMME #08",
    value1: "0.005",
    number14: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number15: "TEMPORARILY SUSPENDED**",
    eth2: "/img/eth@2x.png",
    surname2: "PRICE",
    collection2: "X-FEMME",
    number16: "X-FEMME #09",
    value2: "0.005",
    number17: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number18: "TEMPORARILY SUSPENDED**",
    eth3: "/img/eth@2x.png",
    surname3: "PRICE",
    collection3: "X-FEMME",
    number19: "X-FEMME #10",
    value3: "0.005",
    number20: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number21: "TEMPORARILY SUSPENDED**",
    eth4: "/img/eth@2x.png",
    surname4: "PRICE",
    collection4: "X-FEMME",
    number22: "X-FEMME #11",
    value4: "0.005",
    number23: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number24: "TEMPORARILY SUSPENDED**",
    eth5: "/img/eth@2x.png",
    surname5: "PRICE",
    collection5: "X-FEMME",
    number25: "X-FEMME #12",
    value5: "0.005",
    number26: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number27: "TEMPORARILY SUSPENDED**",
    eth6: "/img/eth@2x.png",
    surname6: "PRICE",
    collection6: "X-FEMME",
    number28: "X-FEMME #13",
    value6: "0.005",
    number29: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number30: "TEMPORARILY SUSPENDED**",
    eth7: "/img/eth@2x.png",
    surname7: "PRICE",
    collection7: "X-FEMME",
    number31: "X-FEMME #14",
    value7: "0.005",
    number32: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number33: "TEMPORARILY SUSPENDED**",
    eth8: "/img/eth@2x.png",
    surname8: "PRICE",
    collection8: "X-FEMME",
    number34: "X-FEMME #15",
    value8: "0.005",
    number35: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number36: "TEMPORARILY SUSPENDED**",
    dao_Blockchain_Projects7: "CALENDAR EVENTS",
    dao_Blockchain_Projects8: "LAST DEVELOPING CONTROL REPORTS",
    report_Topics1: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description1: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics2: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description2: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics3: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description3: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics4: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description4: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics5: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description5: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics6: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description6: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics7: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description7: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics8: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description8: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics9: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description9: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    ayana_Verse1: "/img/ayana-verse-1-1@2x.png",
    group211Props: group212Data,
    group212Props: group213Data,
    group213Props: group214Data,
    group214Props: group215Data,
    group215Props: group216Data,
    group216Props: group218Data,
    group217Props: group219Data,
};

const group122Data = {
    className: "group-12-1",
};

const group2110Data = {
    className: "group-21",
};

const group2111Data = {
    className: "group-2",
};

const group2112Data = {
    className: "group-2",
};

const group2113Data = {
    className: "group-15-1",
};

const group2114Data = {
    className: "group-2",
};

const group2115Data = {
    className: "group-2",
};

const group2116Data = {
    className: "group-2",
};

const group2117Data = {
    className: "group-2",
};

const group2118Data = {
    className: "group-2",
};

const projectsBottom2Data = {
    className: "projects_bottom-1",
};

const coursesBottom2Data = {
    className: "courses_bottom-1",
};

const nftViewBottom2Data = {
    className: "nft_view_bottom-1",
};

const calendarBottom2Data = {
    className: "calendar_bottom-1",
};

const reportsBottom2Data = {
    className: "reports_bottom-1",
};

const nOTEBOOKData = {
    dao_Blockchain_Projects1: "SOME",
    dao_Blockchain_Projects2: "DAILY FOLLOW-UP COURSES",
    graph2: "/img/graph2@2x.png",
    course_Topics1: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description1: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent1: "~30%",
    course_Topics2: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description2: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent2: "~30%",
    course_Topics3: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description3: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent3: "~30%",
    dao_Blockchain_Projects3: <React.Fragment>WELCOME TO MY BLOCKCHAIN UNIVERSE!<br />HERE IS MY OWN PLACE TO MAKE SURE THAT I’M REALLY DEVELOPING CODES, STUDYING AND LEARNING ABOUT BLOCKCHAIN.</React.Fragment>,
    dao_Blockchain_Projects4: "LAST DEVELOPING CONTROL REPORTS",
    report_Topics1: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description1: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics2: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description2: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics3: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description3: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics4: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description4: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics5: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description5: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics6: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description6: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics7: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description7: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics8: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description8: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics9: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description9: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    redes_Socias1: "/img/redes-socias-1@2x.png",
    redes_Socias2: "/img/redes-socias-2@2x.png",
    redes_Socias3: "/img/redes-socias-3@2x.png",
    dao_Blockchain_Projects5: "MY BLOCKCHAIN PROJECTS",
    dao_Blockchain_Projects6: "DAO BLOCKCHAIN",
    number1: "PROJECT #01",
    title1: <React.Fragment>BLOCKCHAIN VACCINE VERIFICATION<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status1: "IN PROGRESS",
    number2: "PROJECT #02",
    title2: <React.Fragment>BLOCKCHAIN FOR SUPPLY CHAIN MANAGEMENT<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status2: "IN PROGRESS",
    number3: "PROJECT #03",
    title3: <React.Fragment>BLOCKCHAIN VOTING APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status3: "IN PROGRESS",
    number4: "PROJECT #04",
    title4: <React.Fragment>BLOCKCHAIN SOCIAL MEDIA APP <br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status4: "IN PROGRESS",
    defi_Blockchain_Projects: "DEFI BLOCKCHAIN",
    number5: "PROJECT #01",
    title5: <React.Fragment>CRYPTOCURRENCY FINANCE PRICE TRACKER<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status5: "IN PROGRESS",
    number6: "PROJECT #02",
    title6: <React.Fragment>BUILD YOUR OWN ETHERSCAN<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status6: "IN PROGRESS",
    number7: "PROJECT #03",
    title7: <React.Fragment>CRYPTOCURRENCY APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status7: "IN PROGRESS",
    number8: "PROJECT #04",
    title8: <React.Fragment>DEFI DASHBOARD ON AVALANCHE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status8: "IN PROGRESS",
    nft_Blockchain_Projects: "NFT BLOCKCHAIN",
    number9: "PROJECT #01",
    title9: <React.Fragment>NFT SMART CONTRACT ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status9: "IN PROGRESS",
    number10: "PROJECT #02",
    title10: <React.Fragment>CREATE GENERATIVE NFTS: ARTWORKS CODE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status10: "IN PROGRESS",
    number11: "PROJECT #03",
    title11: <React.Fragment>FULL WEB3 MINT WEBSITE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status11: "IN PROGRESS",
    number12: "PROJECT #04",
    title12: "",
    fullStackNftMarke: <React.Fragment>FULL STACK NFT MARKETPLACE ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status12: "IN PROGRESS",
    dao_Blockchain_Projects7: "NEXT NFT RELEASES",
    eth1: "/img/eth@2x.png",
    surname1: "PRICE",
    collection1: "X-FEMME",
    number13: "X-FEMME #08",
    value1: "0.005",
    number14: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number15: "TEMPORARILY SUSPENDED**",
    eth2: "/img/eth@2x.png",
    surname2: "PRICE",
    collection2: "X-FEMME",
    number16: "X-FEMME #09",
    value2: "0.005",
    number17: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number18: "TEMPORARILY SUSPENDED**",
    eth3: "/img/eth@2x.png",
    surname3: "PRICE",
    collection3: "X-FEMME",
    number19: "X-FEMME #10",
    value3: "0.005",
    number20: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number21: "TEMPORARILY SUSPENDED**",
    eth4: "/img/eth@2x.png",
    surname4: "PRICE",
    collection4: "X-FEMME",
    number22: "X-FEMME #11",
    value4: "0.005",
    number23: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number24: "TEMPORARILY SUSPENDED**",
    eth5: "/img/eth@2x.png",
    surname5: "PRICE",
    collection5: "X-FEMME",
    number25: "X-FEMME #12",
    value5: "0.005",
    number26: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number27: "TEMPORARILY SUSPENDED**",
    eth6: "/img/eth@2x.png",
    surname6: "PRICE",
    collection6: "X-FEMME",
    number28: "X-FEMME #13",
    value6: "0.005",
    number29: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number30: "TEMPORARILY SUSPENDED**",
    eth7: "/img/eth@2x.png",
    surname7: "PRICE",
    collection7: "X-FEMME",
    number31: "X-FEMME #14",
    value7: "0.005",
    number32: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number33: "TEMPORARILY SUSPENDED**",
    eth8: "/img/eth@2x.png",
    surname8: "PRICE",
    collection8: "X-FEMME",
    number34: "X-FEMME #15",
    value8: "0.005",
    number35: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number36: "TEMPORARILY SUSPENDED**",
    dao_Blockchain_Projects8: "CALENDAR EVENTS",
    spanText1: <React.Fragment>THE PLAN IS NOT TO BE PRETTY. <br />AYANAVERSE IS A HANDS-ON PLACE, THEN IT’S SIMPLE, BUT<br />BELIEVE ME, IT CAN BE A WONDERFUL PLACE FOR WHO WANTS TO DEVELOP A NEW HARDSKILL</React.Fragment>,
    spanText2: " within a fairly short time.",
    ayana_Droid: "/img/ayana-droid@1x.png",
    ayana_Verse1: "/img/ayana-verse-1@2x.png",
    group12Props: group122Data,
    group211Props: group2110Data,
    group212Props: group2111Data,
    group213Props: group2112Data,
    group214Props: group2113Data,
    group215Props: group2114Data,
    group216Props: group2115Data,
    group217Props: group2116Data,
    group218Props: group2117Data,
    group219Props: group2118Data,
    projectsBottomProps: projectsBottom2Data,
    coursesBottomProps: coursesBottom2Data,
    nftViewBottomProps: nftViewBottom2Data,
    calendarBottomProps: calendarBottom2Data,
    reportsBottomProps: reportsBottom2Data,
};

const group123Data = {
    className: "group-12-2",
};

const group2119Data = {
    className: "group-21-1",
};

const group2120Data = {
    className: "group-3",
};

const group2121Data = {
    className: "group-3",
};

const group2122Data = {
    className: "group-15-2",
};

const group2123Data = {
    className: "group-3",
};

const group2124Data = {
    className: "group-3",
};

const group2125Data = {
    className: "group-3",
};

const group2126Data = {
    className: "group-3",
};

const group2127Data = {
    className: "group-3",
};

const projectsBottom3Data = {
    className: "projects_bottom-2",
};

const coursesBottom3Data = {
    className: "courses_bottom-2",
};

const nftViewBottom3Data = {
    className: "nft_view_bottom-2",
};

const calendarBottom3Data = {
    className: "calendar_bottom-2",
};

const reportsBottom3Data = {
    className: "reports_bottom-2",
};

const tABLETData = {
    dao_Blockchain_Projects1: <React.Fragment>WELCOME TO MY BLOCKCHAIN UNIVERSE!<br />HERE IS MY OWN PLACE TO MAKE SURE THAT I’M REALLY DEVELOPING CODES, STUDYING AND LEARNING ABOUT BLOCKCHAIN.</React.Fragment>,
    dao_Blockchain_Projects2: "MY BLOCKCHAIN PROJECTS",
    dao_Blockchain_Projects3: "DAO BLOCKCHAIN",
    number1: "PROJECT #01",
    title1: <React.Fragment>BLOCKCHAIN VACCINE VERIFICATION<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status1: "IN PROGRESS",
    number2: "PROJECT #02",
    title2: <React.Fragment>BLOCKCHAIN FOR SUPPLY CHAIN MANAGEMENT<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status2: "IN PROGRESS",
    number3: "PROJECT #03",
    title3: <React.Fragment>BLOCKCHAIN VOTING APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status3: "IN PROGRESS",
    number4: "PROJECT #04",
    title4: <React.Fragment>BLOCKCHAIN SOCIAL MEDIA APP <br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status4: "IN PROGRESS",
    defi_Blockchain_Projects: "DEFI BLOCKCHAIN",
    number5: "PROJECT #01",
    title5: <React.Fragment>CRYPTOCURRENCY FINANCE PRICE TRACKER<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status5: "IN PROGRESS",
    number6: "PROJECT #02",
    title6: <React.Fragment>BUILD YOUR OWN ETHERSCAN<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status6: "IN PROGRESS",
    number7: "PROJECT #03",
    title7: <React.Fragment>CRYPTOCURRENCY APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status7: "IN PROGRESS",
    number8: "PROJECT #04",
    title8: <React.Fragment>DEFI DASHBOARD ON AVALANCHE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status8: "IN PROGRESS",
    nft_Blockchain_Projects: "NFT BLOCKCHAIN",
    number9: "PROJECT #01",
    title9: <React.Fragment>NFT SMART CONTRACT ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status9: "IN PROGRESS",
    number10: "PROJECT #02",
    title10: <React.Fragment>CREATE GENERATIVE NFTS: ARTWORKS CODE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status10: "IN PROGRESS",
    number11: "PROJECT #03",
    title11: <React.Fragment>FULL WEB3 MINT WEBSITE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status11: "IN PROGRESS",
    number12: "PROJECT #04",
    title12: "",
    fullStackNftMarke: <React.Fragment>FULL STACK NFT MARKETPLACE ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status12: "IN PROGRESS",
    dao_Blockchain_Projects4: "SOME",
    dao_Blockchain_Projects5: "DAILY FOLLOW-UP COURSES",
    graph2: "/img/graph2@2x.png",
    course_Topics21: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description21: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent1: "~30%",
    course_Topics22: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description22: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent2: "~30%",
    course_Topics23: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description23: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent3: "~30%",
    dao_Blockchain_Projects6: "NEXT NFT RELEASES",
    eth1: "/img/eth@2x.png",
    surname1: "PRICE",
    collection1: "X-FEMME",
    number13: "X-FEMME #08",
    value1: "0.005",
    number14: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number15: "TEMPORARILY SUSPENDED**",
    eth2: "/img/eth@2x.png",
    surname2: "PRICE",
    collection2: "X-FEMME",
    number16: "X-FEMME #09",
    value2: "0.005",
    number17: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number18: "TEMPORARILY SUSPENDED**",
    eth3: "/img/eth@2x.png",
    surname3: "PRICE",
    collection3: "X-FEMME",
    number19: "X-FEMME #10",
    value3: "0.005",
    number20: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number21: "TEMPORARILY SUSPENDED**",
    eth4: "/img/eth@2x.png",
    surname4: "PRICE",
    collection4: "X-FEMME",
    number22: "X-FEMME #11",
    value4: "0.005",
    number23: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number24: "TEMPORARILY SUSPENDED**",
    eth5: "/img/eth@2x.png",
    surname5: "PRICE",
    collection5: "X-FEMME",
    number25: "X-FEMME #12",
    value5: "0.005",
    number26: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number27: "TEMPORARILY SUSPENDED**",
    eth6: "/img/eth@2x.png",
    surname6: "PRICE",
    collection6: "X-FEMME",
    number28: "X-FEMME #13",
    value6: "0.005",
    number29: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number30: "TEMPORARILY SUSPENDED**",
    eth7: "/img/eth@2x.png",
    surname7: "PRICE",
    collection7: "X-FEMME",
    number31: "X-FEMME #14",
    value7: "0.005",
    number32: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number33: "TEMPORARILY SUSPENDED**",
    eth8: "/img/eth@2x.png",
    surname8: "PRICE",
    collection8: "X-FEMME",
    number34: "X-FEMME #15",
    value8: "0.005",
    number35: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number36: "TEMPORARILY SUSPENDED**",
    redes_Socias1: "/img/redes-socias-1@2x.png",
    redes_Socias2: "/img/redes-socias-2@2x.png",
    redes_Socias3: "/img/redes-socias-3@2x.png",
    dao_Blockchain_Projects7: "LAST DEVELOPING CONTROL REPORTS",
    report_Topics1: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description1: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics2: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description2: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics3: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description3: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics4: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description4: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics5: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description5: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics6: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description6: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics7: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description7: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics8: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description8: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics9: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description9: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    dao_Blockchain_Projects8: "CALENDAR EVENTS",
    spanText1: <React.Fragment>THE PLAN IS NOT TO BE PRETTY. <br />AYANAVERSE IS A HANDS-ON PLACE, THEN IT’S SIMPLE, BUT<br />BELIEVE ME, IT CAN BE A WONDERFUL PLACE FOR WHO WANTS TO DEVELOP A NEW HARDSKILL</React.Fragment>,
    spanText2: " within a fairly short time.",
    ayana_Droid: "/img/ayana-droid-3@1x.png",
    ayana_Verse1: "/img/ayana-verse-1@2x.png",
    group12Props: group123Data,
    group211Props: group2119Data,
    group212Props: group2120Data,
    group213Props: group2121Data,
    group214Props: group2122Data,
    group215Props: group2123Data,
    group216Props: group2124Data,
    group217Props: group2125Data,
    group218Props: group2126Data,
    group219Props: group2127Data,
    projectsBottomProps: projectsBottom3Data,
    coursesBottomProps: coursesBottom3Data,
    nftViewBottomProps: nftViewBottom3Data,
    calendarBottomProps: calendarBottom3Data,
    reportsBottomProps: reportsBottom3Data,
};

const group124Data = {
    className: "group-12-3",
};

const group2128Data = {
    className: "group-21-2",
};

const group2129Data = {
    className: "group-4",
};

const group2130Data = {
    className: "group-4",
};

const group2131Data = {
    className: "group-15-3",
};

const group2132Data = {
    className: "group-4",
};

const group2133Data = {
    className: "group-4",
};

const group2134Data = {
    className: "group-4",
};

const group2135Data = {
    className: "group-4",
};

const group2136Data = {
    className: "group-4",
};

const projectsBottom22Data = {
    children: "PROJECTS",
};

const coursesBottom22Data = {
    children: "COURSES",
};

const nftViewBottom22Data = {
    children: "NFT VIEW",
};

const calendarBottom22Data = {
    children: "CALENDAR",
};

const reportsBottom22Data = {
    children: "REPORTS",
};

const reportsBottom4Data = {
    className: "reports_bottom-3",
};

const mOBILEData = {
    dao_Blockchain_Projects1: <React.Fragment>WELCOME TO MY BLOCKCHAIN UNIVERSE!<br />HERE IS MY OWN PLACE TO MAKE SURE THAT I’M REALLY DEVELOPING CODES, STUDYING AND LEARNING ABOUT BLOCKCHAIN.</React.Fragment>,
    dao_Blockchain_Projects2: "MY BLOCKCHAIN PROJECTS",
    dao_Blockchain_Projects3: "DAO BLOCKCHAIN",
    number1: "PROJECT #01",
    title1: <React.Fragment>BLOCKCHAIN VACCINE VERIFICATION<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status1: "IN PROGRESS",
    number2: "PROJECT #02",
    title2: <React.Fragment>BLOCKCHAIN FOR SUPPLY CHAIN MANAGEMENT<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status2: "IN PROGRESS",
    number3: "PROJECT #03",
    title3: <React.Fragment>BLOCKCHAIN VOTING APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status3: "IN PROGRESS",
    number4: "PROJECT #04",
    title4: <React.Fragment>BLOCKCHAIN SOCIAL MEDIA APP <br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status4: "IN PROGRESS",
    defi_Blockchain_Projects: "DEFI BLOCKCHAIN",
    number5: "PROJECT #01",
    title5: <React.Fragment>CRYPTOCURRENCY FINANCE PRICE TRACKER<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status5: "IN PROGRESS",
    number6: "PROJECT #02",
    title6: <React.Fragment>BUILD YOUR OWN ETHERSCAN<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status6: "IN PROGRESS",
    number7: "PROJECT #03",
    title7: <React.Fragment>CRYPTOCURRENCY APP<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status7: "IN PROGRESS",
    number8: "PROJECT #04",
    title8: <React.Fragment>DEFI DASHBOARD ON AVALANCHE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status8: "IN PROGRESS",
    nft_Blockchain_Projects: "NFT BLOCKCHAIN",
    number9: "PROJECT #01",
    title9: <React.Fragment>NFT SMART CONTRACT ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status9: "IN PROGRESS",
    number10: "PROJECT #02",
    title10: <React.Fragment>CREATE GENERATIVE NFTS: ARTWORKS CODE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status10: "IN PROGRESS",
    number11: "PROJECT #03",
    title11: <React.Fragment>FULL WEB3 MINT WEBSITE<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status11: "IN PROGRESS",
    number12: "PROJECT #04",
    title12: "",
    fullStackNftMarke: <React.Fragment>FULL STACK NFT MARKETPLACE ON ETHEREUM<br />3 HOURS OF DEVELOPMENT</React.Fragment>,
    status12: "IN PROGRESS",
    dao_Blockchain_Projects4: "SOME",
    dao_Blockchain_Projects5: "DAILY FOLLOW-UP COURSES",
    graph2: "/img/graph2@2x.png",
    course_Topics: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description21: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent1: "~30%",
    course_Topics21: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description22: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent2: "~30%",
    course_Topics22: <React.Fragment>COURSE:<br />LINK:<br />DESCRIPTION:</React.Fragment>,
    course_Description23: <React.Fragment>DESCRIPTION DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:DESCRIPTION:<br />DESCRIPTION:DESCRIPTION:DESCRIPTION:</React.Fragment>,
    percent3: "~30%",
    dao_Blockchain_Projects6: "NEXT NFT RELEASES",
    eth1: "/img/eth@2x.png",
    surname1: "PRICE",
    collection1: "X-FEMME",
    number13: "X-FEMME #08",
    value1: "0.005",
    number14: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number15: "TEMPORARILY SUSPENDED**",
    eth2: "/img/eth@2x.png",
    surname2: "PRICE",
    collection2: "X-FEMME",
    number16: "X-FEMME #09",
    value2: "0.005",
    number17: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number18: "TEMPORARILY SUSPENDED**",
    eth3: "/img/eth@2x.png",
    surname3: "PRICE",
    collection3: "X-FEMME",
    number19: "X-FEMME #10",
    value3: "0.005",
    number20: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number21: "TEMPORARILY SUSPENDED**",
    eth4: "/img/eth@2x.png",
    surname4: "PRICE",
    collection4: "X-FEMME",
    number22: "X-FEMME #11",
    value4: "0.005",
    number23: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number24: "TEMPORARILY SUSPENDED**",
    eth5: "/img/eth@2x.png",
    surname5: "PRICE",
    collection5: "X-FEMME",
    number25: "X-FEMME #12",
    value5: "0.005",
    number26: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number27: "TEMPORARILY SUSPENDED**",
    eth6: "/img/eth@2x.png",
    surname6: "PRICE",
    collection6: "X-FEMME",
    number28: "X-FEMME #13",
    value6: "0.005",
    number29: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number30: "TEMPORARILY SUSPENDED**",
    eth7: "/img/eth@2x.png",
    surname7: "PRICE",
    collection7: "X-FEMME",
    number31: "X-FEMME #14",
    value7: "0.005",
    number32: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number33: "TEMPORARILY SUSPENDED**",
    eth8: "/img/eth@2x.png",
    surname8: "PRICE",
    collection8: "X-FEMME",
    number34: "X-FEMME #15",
    value8: "0.005",
    number35: "**AYANA IS TEMPORARILY SHARED FOR ETHCC APPLICATION",
    number36: "TEMPORARILY SUSPENDED**",
    dao_Blockchain_Projects7: "CALENDAR EVENTS",
    dao_Blockchain_Projects8: "LAST DEVELOPING CONTROL REPORTS",
    report_Topics1: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description1: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics2: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description2: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics3: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description3: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics4: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description4: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics5: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description5: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics6: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description6: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics7: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description7: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics8: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description8: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    report_Topics9: <React.Fragment>PROJECT #01<br />29/06/22<br /><br />REPORT</React.Fragment>,
    report_Description9: <React.Fragment>COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X <br />COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X   COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X COLLECTION X</React.Fragment>,
    redes_Socias1: "/img/redes-socias-1@2x.png",
    redes_Socias2: "/img/redes-socias-2@2x.png",
    redes_Socias3: "/img/redes-socias-3@2x.png",
    ayana_Droid: "/img/ayana-droid-2@1x.png",
    spanText1: <React.Fragment>THE PLAN IS NOT TO BE PRETTY. <br />AYANAVERSE IS A HANDS-ON PLACE, THEN IT’S SIMPLE, BUT<br />BELIEVE ME, IT CAN BE A WONDERFUL PLACE FOR WHO WANTS TO DEVELOP A NEW HARDSKILL</React.Fragment>,
    spanText2: " within a fairly short time.",
    ayana_Verse1: "/img/ayana-verse-1-2@2x.png",
    group12Props: group124Data,
    group211Props: group2128Data,
    group212Props: group2129Data,
    group213Props: group2130Data,
    group214Props: group2131Data,
    group215Props: group2132Data,
    group216Props: group2133Data,
    group217Props: group2134Data,
    group218Props: group2135Data,
    group219Props: group2136Data,
    projectsBottom2Props: projectsBottom22Data,
    coursesBottom2Props: coursesBottom22Data,
    nftViewBottom2Props: nftViewBottom22Data,
    calendarBottom2Props: calendarBottom22Data,
    reportsBottom2Props: reportsBottom22Data,
    reportsBottomProps: reportsBottom4Data,
};

